@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsZXh0YXZlbGxhQGdtYWlsLmNvbSIsIm5hbWUiOiJBbGV4IFRhdmVsbGEiLCJyb2xlIjoiYWRtaW4iLCJzdWIiOjgyLCJpYXQiOjE3NDAwODMyMzksImV4cCI6MTc0MDA4NjgzOX0._rZPGpspv1I078TcDse4fyYBGfmy8oNlKjKTvdwpSZU

### Search coins
GET http://localhost:3333/coins/search?query=bitcoin
Authorization: Bearer {{token}}

### Get coin market (ethereum)
GET http://localhost:3333/coins/ethereum/market?currency=usd
Authorization: Bearer {{token}}

### Get coin market (bitcoin)
GET http://localhost:3333/coins/bitcoin/market?currency=usd
Authorization: Bearer {{token}}

### Get coin market (not found)
GET http://localhost:3333/coins/####/market
Authorization: Bearer {{token}}