@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsZXh0YXZlbGxhQGdtYWlsLmNvbSIsIm5hbWUiOiJBbGV4IFRhdmVsbGEiLCJyb2xlIjoiY3VzdG9tZXIiLCJzdWIiOjgyLCJpYXQiOjE3Mzk5MjQ5NTAsImV4cCI6MTczOTkyODU1MH0.HkZ4G7ugGdtkvF_thlb9bK1ZqtLZVnre75iN0q-EbIw

### Create user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Alex Tavella",
  "email": "alextavella@gmail.com",
  "password": "12345678",
  "role": "customer"
}

### Update user
PUT http://localhost:3333/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Alex Tavella",
  "email": "alextavella@gmail.com",
  "password": "12345678",
  "role": "admin"
}

### List users (name)
GET http://localhost:3333/users/?page=1&pageSize=10&name=ale
Authorization: Bearer {{access_token}}

### List users (role
GET http://localhost:3333/users/?page=1&pageSize=10&role=customer
Authorization: Bearer {{access_token}}