### Create user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Alex Tavella",
  "email": "alextavella@gmail.com",
  "password": "12345678",
  "role": "customer"
}

### Get user (auth)
POST http://localhost:3333/users/auth
Content-Type: application/json

{
  "email": "alextavella@gmail.com",
  "password": "12345678"
}

### Update user
PUT http://localhost:3333/users/2
Content-Type: application/json

{
  "name": "Alex Tavella",
  "email": "alextavella@gmail.com",
  "password": "12345678",
  "role": "admin"
}

### List users (name)
GET http://localhost:3333/users/?page=1&pageSize=10&name=ale

### List users (role
GET http://localhost:3333/users/?page=1&pageSize=10&role=customer