services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: truther
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   container_name: backend
  #   restart: always
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   ports:
  #     - 3333:3333
  #   env_file:
  #     - ./packages/backend/.env
  #   environment:
  #     - NODE_ENV=production
  #     - DB_HOST=mysql
