/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateUser201Role =
  | (typeof CreateUser201Role)[keyof typeof CreateUser201Role]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser201Role = {
  customer: 'customer',
  admin: 'admin',
} as const
