/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetCoinMarketCurrency =
  (typeof GetCoinMarketCurrency)[keyof typeof GetCoinMarketCurrency]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCoinMarketCurrency = {
  usd: 'usd',
  eur: 'eur',
  brl: 'brl',
} as const
