/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetCoinMarket200 = {
  id: string
  name: string
  symbol: string
  image: string
  currentPrice: number
  marketCap: number
  marketCapRank: number
  volume: number
  volumeHigh24h: number
  volumeHLow24h: number
}
