/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetCoinMarketCurrency } from './getCoinMarketCurrency'

export type GetCoinMarketParams = {
  currency?: GetCoinMarketCurrency
}
