/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser200Role } from './getUser200Role'

export type GetUser200 = {
  access_token: string
  uid: number
  name: string
  email: string
  /** @nullable */
  role?: GetUser200Role
}
