/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetUser200Role =
  (typeof GetUser200Role)[keyof typeof GetUser200Role]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser200Role = {
  customer: 'customer',
  admin: 'admin',
} as const
