/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUsersRole = (typeof ListUsersRole)[keyof typeof ListUsersRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsersRole = {
  customer: 'customer',
  admin: 'admin',
} as const
