/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUsers200Pagination = {
  page: number
  pageSize: number
  pageCount: number
  total: number
}
