/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUsers200ItemsItemRole } from './listUsers200ItemsItemRole'

export type ListUsers200ItemsItem = {
  name: string
  email: string
  /** @nullable */
  role?: ListUsers200ItemsItemRole
}
