/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUsers200ItemsItem } from './listUsers200ItemsItem'
import type { ListUsers200Pagination } from './listUsers200Pagination'

export type ListUsers200 = {
  items: ListUsers200ItemsItem[]
  pagination: ListUsers200Pagination
}
