/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUsersRole } from './listUsersRole'

export type ListUsersParams = {
  page?: number
  pageSize?: number
  name?: string
  email?: string
  role?: ListUsersRole
}
