/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ListUsers200ItemsItemRole =
  | (typeof ListUsers200ItemsItemRole)[keyof typeof ListUsers200ItemsItemRole]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers200ItemsItemRole = {
  customer: 'customer',
  admin: 'admin',
} as const
