/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type SearchCoins200ItemsItem = {
  id: string
  name: string
  /** @nullable */
  symbol?: string | null
  /** @nullable */
  image?: string | null
}
