/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UpdateUserBodyRole =
  | (typeof UpdateUserBodyRole)[keyof typeof UpdateUserBodyRole]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserBodyRole = {
  customer: 'customer',
  admin: 'admin',
} as const
