/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUser200Role } from './updateUser200Role'

export type UpdateUser200 = {
  name: string
  email: string
  password: string
  /** @nullable */
  role?: UpdateUser200Role
}
