/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Truther API
 * Truther API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UpdateUser200Role =
  | (typeof UpdateUser200Role)[keyof typeof UpdateUser200Role]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser200Role = {
  customer: 'customer',
  admin: 'admin',
} as const
