openapi: 3.0.0
info:
  title: Truther API
  description: Truther API Documentation
  version: 1.0.0
components:
  schemas: {}
paths:
  /users:
    post:
      operationId: createUser
      summary: Create user
      tags:
        - Users
      description: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum:
                    - customer
                    - admin
                  nullable: true
                  default: customer
              required:
                - name
                - email
                - password
              additionalProperties: false
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  role:
                    type: string
                    enum:
                      - customer
                      - admin
                    nullable: true
                    default: customer
                required:
                  - name
                  - email
                  - password
                additionalProperties: false
  /users/{id}:
    put:
      operationId: updateUser
      summary: Update user
      tags:
        - Users
      description: Update user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum:
                    - customer
                    - admin
                  nullable: true
                  default: customer
              required:
                - name
                - email
                - password
              additionalProperties: false
        required: true
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  role:
                    type: string
                    enum:
                      - customer
                      - admin
                    nullable: true
                    default: customer
                required:
                  - name
                  - email
                  - password
                additionalProperties: false
servers:
  - url: http://localhost:3333
    description: Development
